# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-06 04:12


import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0013_auto_20190201_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetpermission',
            name='submission_set',
            field=models.CharField(blank=True, help_text='Either the name of a submission set (e.g. "comments", "tags", or        "places"). Use a "*" to refer to all things.', max_length=128),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='submission_set',
            field=models.CharField(blank=True, help_text='Either the name of a submission set (e.g. "comments", "tags", or        "places"). Use a "*" to refer to all things.', max_length=128),
        ),
        migrations.AlterField(
            model_name='keypermission',
            name='submission_set',
            field=models.CharField(blank=True, help_text='Either the name of a submission set (e.g. "comments", "tags", or        "places"). Use a "*" to refer to all things.', max_length=128),
        ),
        migrations.AlterField(
            model_name='originpermission',
            name='submission_set',
            field=models.CharField(blank=True, help_text='Either the name of a submission set (e.g. "comments", "tags", or        "places"). Use a "*" to refer to all things.', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username'),
        ),
    ]
