# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0014_auto_20190406_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='jwt_public',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='jwt_secret',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
