# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0014_auto_20190406_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(default='', max_length=128, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'ms_api_flavor',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('is_enabled', models.BooleanField(default=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sa_api_v2.DataSet')),
                ('flavor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='sa_api_v2.Flavor')),
            ],
            options={
                'db_table': 'ms_api_form',
            },
        ),
        migrations.CreateModel(
            name='FormModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ms_api_form_module',
            },
        ),
        migrations.CreateModel(
            name='RadioOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'ms_api_form_module_option_radio',
            },
        ),
        migrations.CreateModel(
            name='InformationalHtmlModule',
            fields=[
                ('formmodule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sa_api_v2.FormModule')),
                ('content', models.TextField(blank=True, default=None)),
            ],
            options={
                'db_table': 'ms_api_form_module_html',
            },
            bases=('sa_api_v2.formmodule',),
        ),
        migrations.CreateModel(
            name='RadioField',
            fields=[
                ('formmodule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sa_api_v2.FormModule')),
                ('key', models.CharField(max_length=128)),
                ('private', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
                ('variant', models.CharField(max_length=128)),
                ('placeholder', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'ms_api_form_module_field_radio',
            },
            bases=('sa_api_v2.formmodule',),
        ),
        migrations.AddField(
            model_name='formmodule',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='sa_api_v2.Form'),
        ),
        migrations.AddField(
            model_name='radiooption',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='sa_api_v2.RadioField'),
        ),
    ]
