# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-08 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0014_auto_20190406_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(default='', max_length=128, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'ms_api_flavor',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('is_enabled', models.BooleanField(default=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sa_api_v2.DataSet')),
                ('flavor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='sa_api_v2.Flavor')),
            ],
            options={
                'db_table': 'ms_api_form',
            },
        ),
        migrations.CreateModel(
            name='FormModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='sa_api_v2.Form')),
            ],
            options={
                'ordering': ['order'],
                'db_table': 'ms_api_form_module',
            },
        ),
        migrations.CreateModel(
            name='HtmlModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default=None)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sa_api_v2.FormModule')),
            ],
            options={
                'db_table': 'ms_api_form_module_html',
            },
        ),
        migrations.CreateModel(
            name='RadioField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('prompt', models.TextField(blank=True, default=b'')),
                ('private', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
                ('variant', models.CharField(choices=[(b'radio', b'a radio selection'), (b'dropdown', b'a dropdown list')], default=b'radio', max_length=128)),
                ('dropdown_placeholder', models.CharField(blank=True, max_length=128, null=True)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sa_api_v2.FormModule')),
            ],
            options={
                'db_table': 'ms_api_form_module_field_radio',
            },
        ),
        migrations.CreateModel(
            name='RadioOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='sa_api_v2.RadioField')),
            ],
            options={
                'db_table': 'ms_api_form_module_option_radio',
            },
        ),
    ]
