# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0014_auto_20190406_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckboxField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('prompt', models.TextField(blank=True, default=b'')),
                ('private', models.BooleanField(default=False, help_text=b'If true, then the submitted data will be flagged as private.')),
                ('required', models.BooleanField(default=False, help_text=b'If true, then the form cannot be submitted unless this field has received a response.')),
            ],
            options={
                'db_table': 'ms_api_form_module_field_checkbox',
            },
        ),
        migrations.CreateModel(
            name='CheckboxOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_to_next_stage', models.BooleanField(default=False, help_text=b'When this option is selected, the form will advance to the next stage.')),
                ('label', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='sa_api_v2.CheckboxField')),
            ],
            options={
                'db_table': 'ms_api_form_module_option_checkbox',
            },
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=128)),
                ('slug', models.SlugField(default='', max_length=128, unique=True)),
            ],
            options={
                'ordering': ['display_name'],
                'db_table': 'ms_api_flavor',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('is_enabled', models.BooleanField(default=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sa_api_v2.DataSet')),
                ('flavor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='sa_api_v2.Flavor')),
            ],
            options={
                'db_table': 'ms_api_form',
            },
        ),
        migrations.CreateModel(
            name='FormStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='sa_api_v2.Form')),
            ],
            options={
                'ordering': ['order'],
                'db_table': 'ms_api_form_stage',
            },
        ),
        migrations.CreateModel(
            name='GroupModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default=b'', help_text=b"For labelling purposes only - won't be used on the form. Use this label to more easily identify this module in the form.", max_length=128)),
            ],
            options={
                'db_table': 'ms_api_form_module_group',
            },
        ),
        migrations.CreateModel(
            name='HtmlModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default=b'', help_text=b"For labelling purposes only - won't be used on the form. Use this label to more easily identify this module in the form.", max_length=128)),
                ('content', models.TextField(help_text=b'Add HTML here that will be displayed on the form. Make sure that the html is valid and sanitized!')),
            ],
            options={
                'db_table': 'ms_api_form_module_html',
            },
        ),
        migrations.CreateModel(
            name='LayerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'ms_api_map_layer_group',
            },
        ),
        migrations.CreateModel(
            name='MapViewport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom', models.PositiveSmallIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('transition_duration', models.PositiveSmallIntegerField()),
                ('bearing', models.PositiveSmallIntegerField()),
                ('pitch', models.PositiveSmallIntegerField()),
                ('stage', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_viewport', to='sa_api_v2.FormStage')),
            ],
            options={
                'db_table': 'ms_api_map_viewport',
            },
        ),
        migrations.CreateModel(
            name='NestedOrderedModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('visible', models.BooleanField(default=True, help_text=b'Determines whether the module is visible by default.')),
                ('checkboxfield', models.ForeignKey(blank=True, help_text=b'Choose a checkbox field. Create a new checkbox field, or select a radiofield that already exists within this flavor. Only one field/module can be selected for this FormModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nested_ordered_modules', to='sa_api_v2.CheckboxField')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='sa_api_v2.GroupModule')),
                ('htmlmodule', models.ForeignKey(blank=True, help_text=b'Choose an html module. Create a new html module, or select an htmlmodule that already exists within this flavor. Only one field/module can be selected for this FormModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nested_ordered_modules', to='sa_api_v2.HtmlModule')),
            ],
            options={
                'ordering': ['order'],
                'db_table': 'ms_api_form_nested_ordered_module',
                'default_related_name': 'nested_ordered_modules',
            },
        ),
        migrations.CreateModel(
            name='OrderedModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('visible', models.BooleanField(default=True, help_text=b'Determines whether the module is visible by default.')),
                ('checkboxfield', models.ForeignKey(blank=True, help_text=b'Choose a checkbox field. Create a new checkbox field, or select a radiofield that already exists within this flavor. Only one field/module can be selected for this FormModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_modules', to='sa_api_v2.CheckboxField')),
                ('groupmodule', models.ForeignKey(blank=True, help_text=b'Choose a group. Create a new radio field, or select a radiofield that already exists within this flavor. Only one field/module can be selected for this FormModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_modules', to='sa_api_v2.GroupModule')),
                ('htmlmodule', models.ForeignKey(blank=True, help_text=b'Choose an html module. Create a new html module, or select an htmlmodule that already exists within this flavor. Only one field/module can be selected for this FormModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_modules', to='sa_api_v2.HtmlModule')),
            ],
            options={
                'ordering': ['order'],
                'db_table': 'ms_api_form_ordered_module',
                'default_related_name': 'ordered_modules',
            },
        ),
        migrations.CreateModel(
            name='RadioField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('prompt', models.TextField(blank=True, default=b'')),
                ('private', models.BooleanField(default=False, help_text=b'If true, then the submitted data will be flagged as private.')),
                ('required', models.BooleanField(default=False, help_text=b'If true, then the form cannot be submitted unless this field has received a response.')),
                ('dropdown_placeholder', models.CharField(blank=True, default=b'', max_length=255)),
                ('variant', models.CharField(choices=[(b'radio', b'a radio selection'), (b'dropdown', b'a dropdown list')], default=b'radio', max_length=128)),
            ],
            options={
                'db_table': 'ms_api_form_module_field_radio',
            },
        ),
        migrations.CreateModel(
            name='RadioOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_to_next_stage', models.BooleanField(default=False, help_text=b'When this option is selected, the form will advance to the next stage.')),
                ('label', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='sa_api_v2.RadioField')),
                ('visibility_triggers', models.ManyToManyField(blank=True, help_text=b"Triggers an update to make the following NestedOrderedModules visible. Only default invisible modules are within this module's group are selectable here.", related_name='_radiooption_visibility_triggers_+', to='sa_api_v2.NestedOrderedModule')),
            ],
            options={
                'db_table': 'ms_api_form_module_option_radio',
            },
        ),
        migrations.CreateModel(
            name='TextAreaField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('prompt', models.TextField(blank=True, default=b'')),
                ('private', models.BooleanField(default=False, help_text=b'If true, then the submitted data will be flagged as private.')),
                ('required', models.BooleanField(default=False, help_text=b'If true, then the form cannot be submitted unless this field has received a response.')),
                ('dropdown_placeholder', models.CharField(blank=True, default=b'', max_length=255)),
            ],
            options={
                'db_table': 'ms_api_form_module_field_textarea',
            },
        ),
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('prompt', models.TextField(blank=True, default=b'')),
                ('private', models.BooleanField(default=False, help_text=b'If true, then the submitted data will be flagged as private.')),
                ('required', models.BooleanField(default=False, help_text=b'If true, then the form cannot be submitted unless this field has received a response.')),
                ('dropdown_placeholder', models.CharField(blank=True, default=b'', max_length=255)),
            ],
            options={
                'db_table': 'ms_api_form_module_field_text',
            },
        ),
        migrations.AddField(
            model_name='orderedmodule',
            name='radiofield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a radio field. Create a new radio field, or select a radiofield that already exists within this flavor. Only one field/module can be selected for this FormModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_modules', to='sa_api_v2.RadioField'),
        ),
        migrations.AddField(
            model_name='orderedmodule',
            name='stage',
            field=models.ForeignKey(help_text=b'Every OrderedModule must belong to a FormStage.', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='sa_api_v2.FormStage'),
        ),
        migrations.AddField(
            model_name='orderedmodule',
            name='textareafield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a textarea field. Create a new textarea field, or select one that already exists within this flavor. Only one field/module can be selected for this FormModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_modules', to='sa_api_v2.TextAreaField'),
        ),
        migrations.AddField(
            model_name='orderedmodule',
            name='textfield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a text field. Create a new text field, or select one that already exists within this flavor. Only one field/module can be selected for this FormModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_modules', to='sa_api_v2.TextField'),
        ),
        migrations.AddField(
            model_name='nestedorderedmodule',
            name='radiofield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a radio field. Create a new radio field, or select a radiofield that already exists within this flavor. Only one field/module can be selected for this FormModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nested_ordered_modules', to='sa_api_v2.RadioField'),
        ),
        migrations.AddField(
            model_name='nestedorderedmodule',
            name='textareafield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a textarea field. Create a new textarea field, or select one that already exists within this flavor. Only one field/module can be selected for this FormModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nested_ordered_modules', to='sa_api_v2.TextAreaField'),
        ),
        migrations.AddField(
            model_name='nestedorderedmodule',
            name='textfield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a text field. Create a new text field, or select one that already exists within this flavor. Only one field/module can be selected for this FormModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nested_ordered_modules', to='sa_api_v2.TextField'),
        ),
        migrations.AddField(
            model_name='formstage',
            name='visible_layer_groups',
            field=models.ManyToManyField(blank=True, help_text=b'A list of layers that will become visible during this stage.', related_name='_formstage_visible_layer_groups_+', to='sa_api_v2.LayerGroup'),
        ),
        migrations.AddField(
            model_name='checkboxoption',
            name='visibility_triggers',
            field=models.ManyToManyField(blank=True, help_text=b"Triggers an update to make the following NestedOrderedModules visible. Only default invisible modules are within this module's group are selectable here.", related_name='_checkboxoption_visibility_triggers_+', to='sa_api_v2.NestedOrderedModule'),
        ),
    ]
