# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-18 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0015_auto_20190517_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'ms_api_map_layer_group',
            },
        ),
        migrations.CreateModel(
            name='MapViewport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom', models.PositiveSmallIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('transition_duration', models.PositiveSmallIntegerField()),
                ('bearing', models.PositiveSmallIntegerField()),
                ('pitch', models.PositiveSmallIntegerField()),
                ('stage', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_viewport', to='sa_api_v2.FormStage')),
            ],
            options={
                'db_table': 'ms_api_map_viewport',
            },
        ),
        migrations.AddField(
            model_name='formstage',
            name='visible_layer_groups',
            field=models.ManyToManyField(blank=True, help_text=b'A list of layers that will become visible during this stage.', related_name='_formstage_visible_layer_groups_+', to='sa_api_v2.LayerGroup'),
        ),
    ]
