# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0015_auto_20190604_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodingField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('prompt', models.TextField(blank=True, default=b'')),
                ('private', models.BooleanField(default=False, help_text=b'If true, then the submitted data will be flagged as private.')),
                ('required', models.BooleanField(default=False, help_text=b'If true, then the form cannot be submitted unless this field has received a response.')),
                ('placeholder', models.CharField(blank=True, default=b'', max_length=255)),
            ],
            options={
                'db_table': 'ms_api_form_module_field_geocoding',
            },
        ),
        migrations.RenameField(
            model_name='textareafield',
            old_name='dropdown_placeholder',
            new_name='placeholder',
        ),
        migrations.RenameField(
            model_name='textfield',
            old_name='dropdown_placeholder',
            new_name='placeholder',
        ),
        migrations.AlterField(
            model_name='nestedorderedmodule',
            name='checkboxfield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a checkbox field by creating a new one, or selecting one that already exists within this flavor. Only one field or one module can be selected for this OrderedModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nested_ordered_modules', to='sa_api_v2.CheckboxField'),
        ),
        migrations.AlterField(
            model_name='nestedorderedmodule',
            name='htmlmodule',
            field=models.ForeignKey(blank=True, help_text=b'Choose a html module by creating a new one, or selecting one that already exists within this flavor. Only one field or one module can be selected for this OrderedModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nested_ordered_modules', to='sa_api_v2.HtmlModule'),
        ),
        migrations.AlterField(
            model_name='nestedorderedmodule',
            name='radiofield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a radio by creating a new one, or selecting one that already exists within this flavor. Only one field or one module can be selected for this OrderedModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nested_ordered_modules', to='sa_api_v2.RadioField'),
        ),
        migrations.AlterField(
            model_name='nestedorderedmodule',
            name='textareafield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a textarea field by creating a new one, or selecting one that already exists within this flavor. Only one field or one module can be selected for this OrderedModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nested_ordered_modules', to='sa_api_v2.TextAreaField'),
        ),
        migrations.AlterField(
            model_name='nestedorderedmodule',
            name='textfield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a text field by creating a new one, or selecting one that already exists within this flavor. Only one field or one module can be selected for this OrderedModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nested_ordered_modules', to='sa_api_v2.TextField'),
        ),
        migrations.AlterField(
            model_name='orderedmodule',
            name='checkboxfield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a checkbox field by creating a new one, or selecting one that already exists within this flavor. Only one field or one module can be selected for this OrderedModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_modules', to='sa_api_v2.CheckboxField'),
        ),
        migrations.AlterField(
            model_name='orderedmodule',
            name='groupmodule',
            field=models.ForeignKey(blank=True, help_text=b'Choose a group module by creating a new one, or selecting one that already exists within this flavor. Only one field or one module can be selected for this OrderedModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_modules', to='sa_api_v2.GroupModule'),
        ),
        migrations.AlterField(
            model_name='orderedmodule',
            name='htmlmodule',
            field=models.ForeignKey(blank=True, help_text=b'Choose a html module by creating a new one, or selecting one that already exists within this flavor. Only one field or one module can be selected for this OrderedModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_modules', to='sa_api_v2.HtmlModule'),
        ),
        migrations.AlterField(
            model_name='orderedmodule',
            name='radiofield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a radio by creating a new one, or selecting one that already exists within this flavor. Only one field or one module can be selected for this OrderedModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_modules', to='sa_api_v2.RadioField'),
        ),
        migrations.AlterField(
            model_name='orderedmodule',
            name='textareafield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a textarea field by creating a new one, or selecting one that already exists within this flavor. Only one field or one module can be selected for this OrderedModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_modules', to='sa_api_v2.TextAreaField'),
        ),
        migrations.AlterField(
            model_name='orderedmodule',
            name='textfield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a text field by creating a new one, or selecting one that already exists within this flavor. Only one field or one module can be selected for this OrderedModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_modules', to='sa_api_v2.TextField'),
        ),
        migrations.AddField(
            model_name='nestedorderedmodule',
            name='geocodingfield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a geocoding field by creating a new one, or selecting one that already exists within this flavor. Only one field or one module can be selected for this OrderedModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nested_ordered_modules', to='sa_api_v2.GeocodingField'),
        ),
        migrations.AddField(
            model_name='orderedmodule',
            name='geocodingfield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a geocoding field by creating a new one, or selecting one that already exists within this flavor. Only one field or one module can be selected for this OrderedModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_modules', to='sa_api_v2.GeocodingField'),
        ),
    ]
