# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-30 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0015_dataset_auth_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeemailtemplate',
            name='default_recipient_email',
            field=models.EmailField(blank=True, default=None, help_text=b'A "Default recipient email" will take precedence             over a Submission\'s "Recipient email field".', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='placeemailtemplate',
            name='recipient_email_field',
            field=models.CharField(blank=True, default=b'', max_length=128),
        ),
    ]
