# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-30 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0015_dataset_auth_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeemailtemplate',
            name='default_recipient_email',
            field=models.CharField(blank=True, default=b'', max_length=128),
        ),
    ]
