# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-30 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0016_auto_20190821_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkboxoption',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='radiooption',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
