# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-27 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0016_auto_20190926_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='skipstagemodule',
            name='stage',
            field=models.ForeignKey(blank=True, help_text=b'If null, skip to the next stage. Otherwise, we skip to the associated FormStage.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sa_api_v2.FormStage'),
        ),
    ]
