# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0016_auto_20190528_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodule',
            name='textfield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a text field. Create a new text field, or select one that already exists within this flavor. Only one field/module can be selected for this FormModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='sa_api_v2.TextField'),
        ),
    ]
