# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-19 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0016_auto_20190917_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkboxoption',
            name='stage_visibility_triggers',
            field=models.ManyToManyField(blank=True, help_text=b"Triggers an update to make the following FormStages visible. Only default invisible stages are within this module's Form are selectable here", related_name='_checkboxoption_stage_visibility_triggers_+', to='sa_api_v2.FormStage'),
        ),
        migrations.AddField(
            model_name='formstage',
            name='label',
            field=models.CharField(blank=True, default=b'', help_text=b'An option label that can be used to describe the form stage. Currently it is only used internally.', max_length=255),
        ),
        migrations.AddField(
            model_name='formstage',
            name='visible',
            field=models.BooleanField(default=True, help_text=b'Determines whether the stage is visible by default.'),
        ),
        migrations.AddField(
            model_name='radiooption',
            name='stage_visibility_triggers',
            field=models.ManyToManyField(blank=True, help_text=b"Triggers an update to make the following FormStages visible. Only default invisible stages are within this module's Form are selectable here", related_name='_radiooption_stage_visibility_triggers_+', to='sa_api_v2.FormStage'),
        ),
    ]
