# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0016_auto_20190605_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layergroup',
            name='label',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
