# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-23 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0016_auto_20190920_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lnglatfield',
            name='info_modal',
        ),
        migrations.RemoveField(
            model_name='nestedorderedmodule',
            name='lnglatfield',
        ),
        migrations.RemoveField(
            model_name='orderedmodule',
            name='lnglatfield',
        ),
        migrations.AddField(
            model_name='formstage',
            name='validate_geometry',
            field=models.BooleanField(default=False, help_text=b'Determines whether we should validate whether a correct lng/lat has been entered at this stage.'),
        ),
        migrations.DeleteModel(
            name='LngLatField',
        ),
    ]
