# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0017_auto_20190605_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text=b"The key onto which the field's response will be saved", max_length=128)),
                ('label', models.TextField(blank=True, default=b'', help_text=b'This label will be used when displaying the submitted form field (eg: "My project idea is:")')),
                ('prompt', models.TextField(blank=True, default=b'', help_text=b'Some helpful text to guide the user on how to fill out this field (eg: "What is your project idea?")')),
                ('private', models.BooleanField(default=False, help_text=b'If true, then the submitted data will be flagged as private')),
                ('required', models.BooleanField(default=False, help_text=b'If true, then the form cannot be submitted unless this field has received a response')),
                ('placeholder', models.CharField(blank=True, default=b'', help_text=b'Used to help guide users on what to type into the form\'s input box (eg: "Enter your email here", "joe@example.com")', max_length=255)),
                ('include_ongoing', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ms_api_form_module_field_date',
            },
        ),
        migrations.CreateModel(
            name='FileField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text=b"The key onto which the field's response will be saved", max_length=128)),
                ('label', models.TextField(blank=True, default=b'', help_text=b'This label will be used when displaying the submitted form field (eg: "My project idea is:")')),
                ('prompt', models.TextField(blank=True, default=b'', help_text=b'Some helpful text to guide the user on how to fill out this field (eg: "What is your project idea?")')),
                ('private', models.BooleanField(default=False, help_text=b'If true, then the submitted data will be flagged as private')),
                ('required', models.BooleanField(default=False, help_text=b'If true, then the form cannot be submitted unless this field has received a response')),
            ],
            options={
                'db_table': 'ms_api_form_module_field_file',
            },
        ),
        migrations.CreateModel(
            name='NumberField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text=b"The key onto which the field's response will be saved", max_length=128)),
                ('label', models.TextField(blank=True, default=b'', help_text=b'This label will be used when displaying the submitted form field (eg: "My project idea is:")')),
                ('prompt', models.TextField(blank=True, default=b'', help_text=b'Some helpful text to guide the user on how to fill out this field (eg: "What is your project idea?")')),
                ('private', models.BooleanField(default=False, help_text=b'If true, then the submitted data will be flagged as private')),
                ('required', models.BooleanField(default=False, help_text=b'If true, then the form cannot be submitted unless this field has received a response')),
                ('placeholder', models.CharField(blank=True, default=b'', help_text=b'Used to help guide users on what to type into the form\'s input box (eg: "Enter your email here", "joe@example.com")', max_length=255)),
                ('minimum', models.IntegerField(blank=True, null=True)),
                ('units', models.CharField(blank=True, default=b'', help_text=b'Units are used for labelling numerical submissions (eg: "13 acres")', max_length=128)),
            ],
            options={
                'db_table': 'ms_api_form_module_field_number',
            },
        ),
        migrations.CreateModel(
            name='SkipStageModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(blank=True, default=b'', help_text=b'The message to be displayed on the form. When clicked, it will skip to the next FormStage. Note that all modules within this FormStage should be optional for this to work properly. (eg: "This section is not relevant to me.")')),
            ],
            options={
                'db_table': 'ms_api_form_module_skip_stage',
            },
        ),
        migrations.RemoveField(
            model_name='checkboxoption',
            name='advance_to_next_stage',
        ),
        migrations.RemoveField(
            model_name='radiooption',
            name='advance_to_next_stage',
        ),
        migrations.AddField(
            model_name='checkboxfield',
            name='label',
            field=models.TextField(blank=True, default=b'', help_text=b'This label will be used when displaying the submitted form field (eg: "My project idea is:")'),
        ),
        migrations.AddField(
            model_name='geocodingfield',
            name='label',
            field=models.TextField(blank=True, default=b'', help_text=b'This label will be used when displaying the submitted form field (eg: "My project idea is:")'),
        ),
        migrations.AddField(
            model_name='radiofield',
            name='label',
            field=models.TextField(blank=True, default=b'', help_text=b'This label will be used when displaying the submitted form field (eg: "My project idea is:")'),
        ),
        migrations.AddField(
            model_name='textareafield',
            name='label',
            field=models.TextField(blank=True, default=b'', help_text=b'This label will be used when displaying the submitted form field (eg: "My project idea is:")'),
        ),
        migrations.AddField(
            model_name='textfield',
            name='label',
            field=models.TextField(blank=True, default=b'', help_text=b'This label will be used when displaying the submitted form field (eg: "My project idea is:")'),
        ),
        migrations.AlterField(
            model_name='checkboxfield',
            name='key',
            field=models.CharField(help_text=b"The key onto which the field's response will be saved", max_length=128),
        ),
        migrations.AlterField(
            model_name='checkboxfield',
            name='private',
            field=models.BooleanField(default=False, help_text=b'If true, then the submitted data will be flagged as private'),
        ),
        migrations.AlterField(
            model_name='checkboxfield',
            name='prompt',
            field=models.TextField(blank=True, default=b'', help_text=b'Some helpful text to guide the user on how to fill out this field (eg: "What is your project idea?")'),
        ),
        migrations.AlterField(
            model_name='checkboxfield',
            name='required',
            field=models.BooleanField(default=False, help_text=b'If true, then the form cannot be submitted unless this field has received a response'),
        ),
        migrations.AlterField(
            model_name='checkboxoption',
            name='label',
            field=models.CharField(help_text=b'For display purposes only. This is how the option will be presented on the form, or labelled in a submission summary.', max_length=128),
        ),
        migrations.AlterField(
            model_name='checkboxoption',
            name='value',
            field=models.CharField(help_text=b"This is the value that will be associated with the field's key.", max_length=128),
        ),
        migrations.AlterField(
            model_name='geocodingfield',
            name='key',
            field=models.CharField(help_text=b"The key onto which the field's response will be saved", max_length=128),
        ),
        migrations.AlterField(
            model_name='geocodingfield',
            name='placeholder',
            field=models.CharField(blank=True, default=b'', help_text=b'Used to help guide users on what to type into the form\'s input box (eg: "Enter your email here", "joe@example.com")', max_length=255),
        ),
        migrations.AlterField(
            model_name='geocodingfield',
            name='private',
            field=models.BooleanField(default=False, help_text=b'If true, then the submitted data will be flagged as private'),
        ),
        migrations.AlterField(
            model_name='geocodingfield',
            name='prompt',
            field=models.TextField(blank=True, default=b'', help_text=b'Some helpful text to guide the user on how to fill out this field (eg: "What is your project idea?")'),
        ),
        migrations.AlterField(
            model_name='geocodingfield',
            name='required',
            field=models.BooleanField(default=False, help_text=b'If true, then the form cannot be submitted unless this field has received a response'),
        ),
        migrations.AlterField(
            model_name='groupmodule',
            name='label',
            field=models.CharField(blank=True, default=b'', help_text=b"For naming purposes only - this won't be displayed to end users. Use this label to more easily identify this module whle building the form.", max_length=128),
        ),
        migrations.AlterField(
            model_name='htmlmodule',
            name='label',
            field=models.CharField(blank=True, default=b'', help_text=b"For naming purposes only - this won't be displayed to end users. Use this label to more easily identify this module whle building the form.", max_length=128),
        ),
        migrations.AlterField(
            model_name='origin',
            name='pattern',
            field=models.CharField(help_text=b'The origin pattern, e.g., https://*.mapseed.org, http://localhost:*, http*://map.pugetsoundkeeper.org', max_length=100),
        ),
        migrations.AlterField(
            model_name='radiofield',
            name='dropdown_placeholder',
            field=models.CharField(blank=True, default=b'', help_text=b'Used to help guide users on what to type into the form\'s input box (eg: "Enter your email here", "joe@example.com")', max_length=255),
        ),
        migrations.AlterField(
            model_name='radiofield',
            name='key',
            field=models.CharField(help_text=b"The key onto which the field's response will be saved", max_length=128),
        ),
        migrations.AlterField(
            model_name='radiofield',
            name='private',
            field=models.BooleanField(default=False, help_text=b'If true, then the submitted data will be flagged as private'),
        ),
        migrations.AlterField(
            model_name='radiofield',
            name='prompt',
            field=models.TextField(blank=True, default=b'', help_text=b'Some helpful text to guide the user on how to fill out this field (eg: "What is your project idea?")'),
        ),
        migrations.AlterField(
            model_name='radiofield',
            name='required',
            field=models.BooleanField(default=False, help_text=b'If true, then the form cannot be submitted unless this field has received a response'),
        ),
        migrations.AlterField(
            model_name='radiofield',
            name='variant',
            field=models.CharField(choices=[(b'radio', b'a radio selection'), (b'dropdown', b'a dropdown list'), (b'toggle', b'a toggle switch, choosing one of 2 choices')], default=b'radio', max_length=128),
        ),
        migrations.AlterField(
            model_name='radiooption',
            name='label',
            field=models.CharField(help_text=b'For display purposes only. This is how the option will be presented on the form, or labelled in a submission summary.', max_length=128),
        ),
        migrations.AlterField(
            model_name='radiooption',
            name='value',
            field=models.CharField(help_text=b"This is the value that will be associated with the field's key.", max_length=128),
        ),
        migrations.AlterField(
            model_name='textareafield',
            name='key',
            field=models.CharField(help_text=b"The key onto which the field's response will be saved", max_length=128),
        ),
        migrations.AlterField(
            model_name='textareafield',
            name='placeholder',
            field=models.CharField(blank=True, default=b'', help_text=b'Used to help guide users on what to type into the form\'s input box (eg: "Enter your email here", "joe@example.com")', max_length=255),
        ),
        migrations.AlterField(
            model_name='textareafield',
            name='private',
            field=models.BooleanField(default=False, help_text=b'If true, then the submitted data will be flagged as private'),
        ),
        migrations.AlterField(
            model_name='textareafield',
            name='prompt',
            field=models.TextField(blank=True, default=b'', help_text=b'Some helpful text to guide the user on how to fill out this field (eg: "What is your project idea?")'),
        ),
        migrations.AlterField(
            model_name='textareafield',
            name='required',
            field=models.BooleanField(default=False, help_text=b'If true, then the form cannot be submitted unless this field has received a response'),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='key',
            field=models.CharField(help_text=b"The key onto which the field's response will be saved", max_length=128),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='placeholder',
            field=models.CharField(blank=True, default=b'', help_text=b'Used to help guide users on what to type into the form\'s input box (eg: "Enter your email here", "joe@example.com")', max_length=255),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='private',
            field=models.BooleanField(default=False, help_text=b'If true, then the submitted data will be flagged as private'),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='prompt',
            field=models.TextField(blank=True, default=b'', help_text=b'Some helpful text to guide the user on how to fill out this field (eg: "What is your project idea?")'),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='required',
            field=models.BooleanField(default=False, help_text=b'If true, then the form cannot be submitted unless this field has received a response'),
        ),
        migrations.AddField(
            model_name='nestedorderedmodule',
            name='datefield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a date by creating a new one, or selecting one that already exists within this flavor. Only one field or one module can be selected for this OrderedModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nested_ordered_modules', to='sa_api_v2.DateField'),
        ),
        migrations.AddField(
            model_name='nestedorderedmodule',
            name='filefield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a file by creating a new one, or selecting one that already exists within this flavor. Only one field or one module can be selected for this OrderedModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nested_ordered_modules', to='sa_api_v2.FileField'),
        ),
        migrations.AddField(
            model_name='nestedorderedmodule',
            name='numberfield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a number by creating a new one, or selecting one that already exists within this flavor. Only one field or one module can be selected for this OrderedModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nested_ordered_modules', to='sa_api_v2.NumberField'),
        ),
        migrations.AddField(
            model_name='nestedorderedmodule',
            name='skipstagemodule',
            field=models.ForeignKey(blank=True, help_text=b'Choose a skip stage module by creating a new one, or selecting one that already exists within this flavor. Only one field or one module can be selected for this OrderedModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nested_ordered_modules', to='sa_api_v2.SkipStageModule'),
        ),
        migrations.AddField(
            model_name='orderedmodule',
            name='datefield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a date by creating a new one, or selecting one that already exists within this flavor. Only one field or one module can be selected for this OrderedModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_modules', to='sa_api_v2.DateField'),
        ),
        migrations.AddField(
            model_name='orderedmodule',
            name='filefield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a file by creating a new one, or selecting one that already exists within this flavor. Only one field or one module can be selected for this OrderedModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_modules', to='sa_api_v2.FileField'),
        ),
        migrations.AddField(
            model_name='orderedmodule',
            name='numberfield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a number by creating a new one, or selecting one that already exists within this flavor. Only one field or one module can be selected for this OrderedModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_modules', to='sa_api_v2.NumberField'),
        ),
        migrations.AddField(
            model_name='orderedmodule',
            name='skipstagemodule',
            field=models.ForeignKey(blank=True, help_text=b'Choose a skip stage module by creating a new one, or selecting one that already exists within this flavor. Only one field or one module can be selected for this OrderedModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_modules', to='sa_api_v2.SkipStageModule'),
        ),
    ]
