# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-11 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0017_auto_20191009_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedmodule',
            name='include_on_list',
            field=models.BooleanField(default=False, help_text=b'If true, then include this field when rendering list items.'),
        ),
    ]
