# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-16 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0017_auto_20191015_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiofield',
            name='variant',
            field=models.CharField(choices=[(b'RA', b'a radio selection'), (b'DR', b'a dropdown list'), (b'TO', b'a toggle switch, choosing one of 2 choices')], default=b'RA', max_length=127),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='variant',
            field=models.CharField(blank=True, choices=[(b'EM', b'Email'), (b'PH', b'Phone'), (b'AD', b'Address')], max_length=127),
        ),
    ]
