# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-23 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0017_auto_20190923_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='dataset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sa_api_v2.DataSet'),
        ),
    ]
