# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-20 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0017_auto_20190919_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocodingfield',
            name='reverse_geocode',
            field=models.BooleanField(default=True, help_text=b"Inidicates whether the field will auto-update with a new address based on the map's location."),
        ),
    ]
