# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0017_formmodule_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckboxField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('prompt', models.TextField(blank=True, default=b'')),
                ('private', models.BooleanField(default=False, help_text=b'If true, then the submitted data will be flagged as private.')),
                ('required', models.BooleanField(default=False, help_text=b'If true, then the form cannot be submitted unless this field has received a response.')),
            ],
            options={
                'db_table': 'ms_api_form_module_field_checkbox',
            },
        ),
        migrations.CreateModel(
            name='CheckboxOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_to_next_stage', models.BooleanField(default=False, help_text=b'When this option is selected, the form will advance to the next stage.')),
                ('label', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='sa_api_v2.CheckboxField')),
                ('visibility_triggers', models.ManyToManyField(blank=True, help_text=b'If this FormFieldOption is selected, the following FormModules will become visible. Only default invisible modules are selectable here.', related_name='_checkboxoption_visibility_triggers_+', to='sa_api_v2.FormModule')),
            ],
            options={
                'db_table': 'ms_api_form_module_option_checkbox',
            },
        ),
        migrations.CreateModel(
            name='TextAreaField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('prompt', models.TextField(blank=True, default=b'')),
                ('private', models.BooleanField(default=False, help_text=b'If true, then the submitted data will be flagged as private.')),
                ('required', models.BooleanField(default=False, help_text=b'If true, then the form cannot be submitted unless this field has received a response.')),
                ('dropdown_placeholder', models.CharField(blank=True, default=b'', max_length=255)),
            ],
            options={
                'db_table': 'ms_api_form_module_field_textarea',
            },
        ),
        migrations.AddField(
            model_name='textfield',
            name='dropdown_placeholder',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='radiofield',
            name='dropdown_placeholder',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='formmodule',
            name='checkboxfield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a checkbox field. Create a new checkbox field, or select a radiofield that already exists within this flavor. Only one field/module can be selected for this FormModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='sa_api_v2.CheckboxField'),
        ),
        migrations.AddField(
            model_name='formmodule',
            name='textareafield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a textarea field. Create a new textarea field, or select one that already exists within this flavor. Only one field/module can be selected for this FormModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='sa_api_v2.TextAreaField'),
        ),
    ]
