# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-09 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0017_auto_20191009_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressfield',
            name='prompt',
            field=models.CharField(blank=True, default=b'', help_text=b'Some helpful text to guide the user on how to fill out this field (eg: "What is your project idea?")', max_length=512),
        ),
        migrations.AlterField(
            model_name='checkboxfield',
            name='prompt',
            field=models.CharField(blank=True, default=b'', help_text=b'Some helpful text to guide the user on how to fill out this field (eg: "What is your project idea?")', max_length=512),
        ),
        migrations.AlterField(
            model_name='datefield',
            name='prompt',
            field=models.CharField(blank=True, default=b'', help_text=b'Some helpful text to guide the user on how to fill out this field (eg: "What is your project idea?")', max_length=512),
        ),
        migrations.AlterField(
            model_name='filefield',
            name='prompt',
            field=models.CharField(blank=True, default=b'', help_text=b'Some helpful text to guide the user on how to fill out this field (eg: "What is your project idea?")', max_length=512),
        ),
        migrations.AlterField(
            model_name='numberfield',
            name='prompt',
            field=models.CharField(blank=True, default=b'', help_text=b'Some helpful text to guide the user on how to fill out this field (eg: "What is your project idea?")', max_length=512),
        ),
        migrations.AlterField(
            model_name='radiofield',
            name='prompt',
            field=models.CharField(blank=True, default=b'', help_text=b'Some helpful text to guide the user on how to fill out this field (eg: "What is your project idea?")', max_length=512),
        ),
        migrations.AlterField(
            model_name='textareafield',
            name='prompt',
            field=models.CharField(blank=True, default=b'', help_text=b'Some helpful text to guide the user on how to fill out this field (eg: "What is your project idea?")', max_length=512),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='prompt',
            field=models.CharField(blank=True, default=b'', help_text=b'Some helpful text to guide the user on how to fill out this field (eg: "What is your project idea?")', max_length=512),
        ),
    ]
