# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-09 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0017_auto_20191001_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='textareafield',
            name='rich_text',
            field=models.BooleanField(default=False, help_text=b'Determines whether the field allows for rich text input.'),
        ),
        migrations.AlterField(
            model_name='skipstagemodule',
            name='label',
            field=models.TextField(blank=True, default=b'', help_text=b'The message to be displayed on the form. When clicked, it will skip to the appropriate FormStage. Note that all modules within this FormStage should be optional for this to work properly. (eg: "This section is not relevant to me.")'),
        ),
    ]
