# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-23 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0018_auto_20190923_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkboxoption',
            name='icon',
            field=models.CharField(blank=True, default=b'', help_text=b"An URL for the location of this option's icon. This field is optional.", max_length=127),
        ),
        migrations.AddField(
            model_name='form',
            name='icon',
            field=models.CharField(blank=True, default=b'', help_text=b"An URL for the location of this forms's icon. Useful when selecting one of multiple forms on a flavor. This field is optional.", max_length=127),
        ),
        migrations.AddField(
            model_name='radiooption',
            name='icon',
            field=models.CharField(blank=True, default=b'', help_text=b"An URL for the location of this option's icon. This field is optional.", max_length=127),
        ),
    ]
