# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-20 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0018_geocodingfield_reverse_geocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(help_text=b'This is the label that the submit button will have', max_length=127)),
                ('content', models.TextField(help_text=b'Add HTML here that will be displayed as a modal alongside the FormField. Make sure that the html is valid and sanitized!')),
            ],
            options={
                'db_table': 'ms_api_form_field_modal',
            },
        ),
        migrations.AddField(
            model_name='checkboxfield',
            name='info_modal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sa_api_v2.Modal'),
        ),
        migrations.AddField(
            model_name='datefield',
            name='info_modal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sa_api_v2.Modal'),
        ),
        migrations.AddField(
            model_name='filefield',
            name='info_modal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sa_api_v2.Modal'),
        ),
        migrations.AddField(
            model_name='geocodingfield',
            name='info_modal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sa_api_v2.Modal'),
        ),
        migrations.AddField(
            model_name='latlngfield',
            name='info_modal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sa_api_v2.Modal'),
        ),
        migrations.AddField(
            model_name='numberfield',
            name='info_modal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sa_api_v2.Modal'),
        ),
        migrations.AddField(
            model_name='radiofield',
            name='info_modal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sa_api_v2.Modal'),
        ),
        migrations.AddField(
            model_name='textareafield',
            name='info_modal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sa_api_v2.Modal'),
        ),
        migrations.AddField(
            model_name='textfield',
            name='info_modal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sa_api_v2.Modal'),
        ),
    ]
