# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0018_auto_20190607_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='datefield',
            name='form_format',
            field=models.CharField(blank=True, default=b'', help_text=b'Formatting of the date that will be required for the input form', max_length=24),
        ),
        migrations.AddField(
            model_name='datefield',
            name='label_format',
            field=models.CharField(blank=True, default=b'', help_text=b'Formatting of the date that will be used on the label', max_length=24),
        ),
    ]
