# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-01 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0018_auto_20190530_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormGroupModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('visible', models.BooleanField(default=True, help_text=b'Determines whether the module is visible by default.')),
                ('checkboxfield', models.ForeignKey(blank=True, help_text=b'Choose a checkbox field. Create a new checkbox field, or select a radiofield that already exists within this flavor. Only one field/module can be selected for this FormModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_modules', to='sa_api_v2.CheckboxField')),
            ],
            options={
                'ordering': ['order'],
                'db_table': 'ms_api_form_group_module',
                'default_related_name': 'group_modules',
            },
        ),
        migrations.CreateModel(
            name='FormStageModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('visible', models.BooleanField(default=True, help_text=b'Determines whether the module is visible by default.')),
                ('checkboxfield', models.ForeignKey(blank=True, help_text=b'Choose a checkbox field. Create a new checkbox field, or select a radiofield that already exists within this flavor. Only one field/module can be selected for this FormModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_modules', to='sa_api_v2.CheckboxField')),
            ],
            options={
                'ordering': ['order'],
                'db_table': 'ms_api_form_stage_module',
                'default_related_name': 'stage_modules',
            },
        ),
        migrations.CreateModel(
            name='GroupModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default=b'', help_text=b"For labelling purposes only - won't be used on the form. Use this label to more easily identify this module in the form.", max_length=128)),
            ],
            options={
                'db_table': 'ms_api_form_module_group',
            },
        ),
        migrations.RemoveField(
            model_name='formmodule',
            name='checkboxfield',
        ),
        migrations.RemoveField(
            model_name='formmodule',
            name='htmlmodule',
        ),
        migrations.RemoveField(
            model_name='formmodule',
            name='radiofield',
        ),
        migrations.RemoveField(
            model_name='formmodule',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='formmodule',
            name='textareafield',
        ),
        migrations.RemoveField(
            model_name='formmodule',
            name='textfield',
        ),
        migrations.AlterField(
            model_name='checkboxoption',
            name='visibility_triggers',
            field=models.ManyToManyField(blank=True, help_text=b'If this FormFieldOption is selected, the following FormGroupModules will become visible. Only default invisible modules are selectable here.', related_name='_checkboxoption_visibility_triggers_+', to='sa_api_v2.FormGroupModule'),
        ),
        migrations.AlterField(
            model_name='htmlmodule',
            name='label',
            field=models.CharField(blank=True, default=b'', help_text=b"For labelling purposes only - won't be used on the form. Use this label to more easily identify this module in the form.", max_length=128),
        ),
        migrations.AlterField(
            model_name='radiooption',
            name='visibility_triggers',
            field=models.ManyToManyField(blank=True, help_text=b'If this FormFieldOption is selected, the following FormGroupModules will become visible. Only default invisible modules are selectable here.', related_name='_radiooption_visibility_triggers_+', to='sa_api_v2.FormGroupModule'),
        ),
        migrations.DeleteModel(
            name='FormModule',
        ),
        migrations.AddField(
            model_name='formstagemodule',
            name='groupmodule',
            field=models.ForeignKey(blank=True, help_text=b'Choose a group. Create a new radio field, or select a radiofield that already exists within this flavor. Only one field/module can be selected for this FormModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_modules', to='sa_api_v2.GroupModule'),
        ),
        migrations.AddField(
            model_name='formstagemodule',
            name='htmlmodule',
            field=models.ForeignKey(blank=True, help_text=b'Choose an html module. Create a new html module, or select an htmlmodule that already exists within this flavor. Only one field/module can be selected for this FormModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_modules', to='sa_api_v2.HtmlModule'),
        ),
        migrations.AddField(
            model_name='formstagemodule',
            name='radiofield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a radio field. Create a new radio field, or select a radiofield that already exists within this flavor. Only one field/module can be selected for this FormModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_modules', to='sa_api_v2.RadioField'),
        ),
        migrations.AddField(
            model_name='formstagemodule',
            name='stage',
            field=models.ForeignKey(help_text=b'Every FormStageModule must belong to a FormStage.', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='sa_api_v2.FormStage'),
        ),
        migrations.AddField(
            model_name='formstagemodule',
            name='textareafield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a textarea field. Create a new textarea field, or select one that already exists within this flavor. Only one field/module can be selected for this FormModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_modules', to='sa_api_v2.TextAreaField'),
        ),
        migrations.AddField(
            model_name='formstagemodule',
            name='textfield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a text field. Create a new text field, or select one that already exists within this flavor. Only one field/module can be selected for this FormModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_modules', to='sa_api_v2.TextField'),
        ),
        migrations.AddField(
            model_name='formgroupmodule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='sa_api_v2.GroupModule'),
        ),
        migrations.AddField(
            model_name='formgroupmodule',
            name='htmlmodule',
            field=models.ForeignKey(blank=True, help_text=b'Choose an html module. Create a new html module, or select an htmlmodule that already exists within this flavor. Only one field/module can be selected for this FormModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_modules', to='sa_api_v2.HtmlModule'),
        ),
        migrations.AddField(
            model_name='formgroupmodule',
            name='radiofield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a radio field. Create a new radio field, or select a radiofield that already exists within this flavor. Only one field/module can be selected for this FormModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_modules', to='sa_api_v2.RadioField'),
        ),
        migrations.AddField(
            model_name='formgroupmodule',
            name='textareafield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a textarea field. Create a new textarea field, or select one that already exists within this flavor. Only one field/module can be selected for this FormModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_modules', to='sa_api_v2.TextAreaField'),
        ),
        migrations.AddField(
            model_name='formgroupmodule',
            name='textfield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a text field. Create a new text field, or select one that already exists within this flavor. Only one field/module can be selected for this FormModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_modules', to='sa_api_v2.TextField'),
        ),
    ]
