# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-09 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0018_auto_20191009_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiooption',
            name='label',
            field=models.CharField(help_text=b'For display purposes only. This is how the option will be presented on the form, or labelled in a submission summary.', max_length=255),
        ),
    ]
