# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-20 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0019_auto_20190920_0148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeocodingField',
            new_name='AddressField',
        ),
        migrations.RemoveField(
            model_name='nestedorderedmodule',
            name='geocodingfield',
        ),
        migrations.RemoveField(
            model_name='orderedmodule',
            name='geocodingfield',
        ),
        migrations.AddField(
            model_name='nestedorderedmodule',
            name='addressfield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a address field by creating a new one, or selecting one that already exists within this flavor. Only one field or one module can be selected for this OrderedModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nested_ordered_modules', to='sa_api_v2.AddressField'),
        ),
        migrations.AddField(
            model_name='orderedmodule',
            name='addressfield',
            field=models.ForeignKey(blank=True, help_text=b'Choose a address field by creating a new one, or selecting one that already exists within this flavor. Only one field or one module can be selected for this OrderedModule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_modules', to='sa_api_v2.AddressField'),
        ),
        migrations.AlterModelTable(
            name='addressfield',
            table='ms_api_form_module_field_address',
        ),
    ]
