# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-06 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0019_formstage_header_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiofield',
            name='variant',
            field=models.CharField(choices=[(b'RA', b'a radio selection'), (b'DR', b'a dropdown list'), (b'TO', b'a toggle switch, choosing one of 2 choices'), (b'AD', b'a dropdown list that allows fuzzy searching through the items')], default=b'RA', max_length=127),
        ),
    ]
