# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-07 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0020_auto_20191106_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressfield',
            name='placeholder',
            field=models.CharField(blank=True, help_text=b'Used to help guide users on what to type into the form\'s input box (eg: "Enter your email here", "joe@example.com")', max_length=512),
        ),
        migrations.AlterField(
            model_name='datefield',
            name='placeholder',
            field=models.CharField(blank=True, help_text=b'Used to help guide users on what to type into the form\'s input box (eg: "Enter your email here", "joe@example.com")', max_length=512),
        ),
        migrations.AlterField(
            model_name='numberfield',
            name='placeholder',
            field=models.CharField(blank=True, help_text=b'Used to help guide users on what to type into the form\'s input box (eg: "Enter your email here", "joe@example.com")', max_length=512),
        ),
        migrations.AlterField(
            model_name='radiofield',
            name='dropdown_placeholder',
            field=models.CharField(blank=True, help_text=b'Used to help guide users on what to type into the form\'s input box (eg: "Enter your email here", "joe@example.com")', max_length=512),
        ),
        migrations.AlterField(
            model_name='textareafield',
            name='placeholder',
            field=models.CharField(blank=True, help_text=b'Used to help guide users on what to type into the form\'s input box (eg: "Enter your email here", "joe@example.com")', max_length=512),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='placeholder',
            field=models.CharField(blank=True, help_text=b'Used to help guide users on what to type into the form\'s input box (eg: "Enter your email here", "joe@example.com")', max_length=512),
        ),
    ]
